# Generated by Django 5.1 on 2024-08-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(unique=True)),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=255)),
                ('league_country', models.CharField(max_length=255)),
                ('league_logo', models.URLField(blank=True, null=True)),
                ('league_country_flag', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
                ('status_short', models.CharField(max_length=10)),
                ('status_long', models.CharField(max_length=255)),
                ('status_elapsed', models.IntegerField(blank=True, null=True)),
                ('status_type', models.CharField(max_length=50)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=255, null=True)),
                ('home_team_id', models.IntegerField()),
                ('home_team_name', models.CharField(max_length=255)),
                ('home_team_logo', models.URLField(blank=True, null=True)),
                ('home_team_winner', models.BooleanField(blank=True, null=True)),
                ('away_team_id', models.IntegerField()),
                ('away_team_name', models.CharField(max_length=255)),
                ('away_team_logo', models.URLField(blank=True, null=True)),
                ('away_team_winner', models.BooleanField(blank=True, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('halftime_home', models.IntegerField(blank=True, null=True)),
                ('halftime_away', models.IntegerField(blank=True, null=True)),
                ('fulltime_home', models.IntegerField(blank=True, null=True)),
                ('fulltime_away', models.IntegerField(blank=True, null=True)),
                ('extratime_home', models.IntegerField(blank=True, null=True)),
                ('extratime_away', models.IntegerField(blank=True, null=True)),
                ('penalty_home', models.IntegerField(blank=True, null=True)),
                ('penalty_away', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
